import * as z from "zod";
import { ComponentType } from "@prisma/client"; // Assuming ComponentType enum is generated by Prisma client

// Base schema for common properties
const baseComponentSchema = {
  pageId: z.string().uuid({ message: "Invalid Page ID" }),
  type: z.nativeEnum(ComponentType, { message: "Invalid Component Type" }),
  order: z
    .number()
    .int()
    .min(0, { message: "Order must be a non-negative integer" }),
  content: z.record(z.any(), { message: "Content must be a JSON object" }), // General JSON object, specific validation per type later
  styles: z
    .record(z.any(), { message: "Styles must be a JSON object" })
    .optional()
    .nullable(), // General JSON object for styles
};

export const createPageComponentSchema = z.object(baseComponentSchema);

export type CreatePageComponentInput = z.infer<
  typeof createPageComponentSchema
>;

// Optional: Define more specific schemas per component type if needed for creation
// For example, if certain content fields are mandatory for a TEXT component at creation:
export const createTextComponentSchema = z.object({
  ...baseComponentSchema,
  type: z.literal(ComponentType.TEXT),
  content: z.object({
    textValue: z.string().min(1, { message: "Text value cannot be empty" }),
    alignment: z.enum(["left", "center", "right"]).optional().default("left"),
  }),
  styles: z
    .object({
      gridColumnSpan: z.number().int().min(1).optional().default(1),
      gridRowSpan: z.number().int().min(1).optional().default(1),
      // Add other text-specific style validations here
    })
    .optional()
    .nullable(),
});

// Add similar specific schemas for IMAGE, VIDEO, LINK, SOCIALS as they are developed.

// For now, the API will use the more generic createPageComponentSchema,
// and detailed content/style validation can occur within the API route based on the type.
// Or, the frontend can be responsible for sending the correct content structure based on type.

export const updatePageComponentSchema = z.object({
  // pageId and type are typically not updatable directly, or handled via specific logic if allowed.
  // For this schema, we assume they are fixed after creation or updated via other means.
  order: z
    .number()
    .int()
    .min(0, { message: "Order must be a non-negative integer" })
    .optional(),
  content: z
    .record(z.any(), { message: "Content must be a JSON object" })
    .optional(),
  styles: z
    .record(z.any(), { message: "Styles must be a JSON object" })
    .optional()
    .nullable(),
});

export type UpdatePageComponentInput = z.infer<
  typeof updatePageComponentSchema
>;

// Example of a more specific update schema for a TEXT component (allowing partial updates)
export const updateTextComponentSchema = z.object({
  order: z.number().int().min(0).optional(),
  content: z
    .object({
      textValue: z.string().min(1).optional(),
      alignment: z.enum(["left", "center", "right"]).optional(),
    })
    .deepPartial()
    .optional(), // deepPartial allows any subset of content fields to be updated
  styles: z
    .object({
      gridColumnSpan: z.number().int().min(1).optional(),
      gridRowSpan: z.number().int().min(1).optional(),
      // Add other text-specific style validations here
    })
    .deepPartial()
    .optional()
    .nullable(),
});

export const reorderPageComponentsSchema = z.object({
  pageId: z.string().uuid({ message: "Invalid Page ID" }), // pageId will come from URL params, but good to have if body needs it directly
  components: z
    .array(
      z.object({
        id: z.string().uuid({ message: "Invalid Component ID" }),
        order: z
          .number()
          .int()
          .min(0, { message: "Order must be a non-negative integer" }),
      })
    )
    .min(1, { message: "Components array cannot be empty" }),
});

export type ReorderPageComponentsInput = z.infer<
  typeof reorderPageComponentsSchema
>;
