import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./components/auth/SessionProviderWrapper"; // Import the wrapper
import { Toaster } from "~/components/ui/sonner"; // Changed path to ~/

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Linktree Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>
          {" "}
          {/* Wrap children with SessionProviderWrapper */}
          {children}
          <Toaster /> {/* Add Toaster for notifications */}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
